; Основные настройки PHP
memory_limit = 512M
max_execution_time = 120
upload_max_filesize = 64M
post_max_size = 64M
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
error_log = /var/log/php/error.log
default_charset = "UTF-8"
date.timezone = UTC

; Настройки Xdebug
xdebug.mode = off
xdebug.start_with_request = no
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.idekey = PHPSTORM

; Настройки сессий
session.save_handler = redis
session.save_path = "tcp://redis:6379"
session.gc_maxlifetime = 1440
session.gc_probability = 1
session.gc_divisor = 100
session.cookie_secure = Off
session.cookie_httponly = On
session.cookie_samesite = "Lax"
session.use_strict_mode = 1
session.sid_bits_per_character = 5
session.sid_length = 48
session.cache_limiter = nocache
session.use_only_cookies = 1

; Настройки OPcache
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.interned_strings_buffer = 16
opcache.fast_shutdown = 1

; Настройки Redis
redis.arrays.names = ""
redis.arrays.hosts = ""
redis.arrays.previous = ""
redis.arrays.functions = ""
redis.arrays.index = ""
redis.arrays.autorehash = ""
redis.arrays.pconnect = ""
redis.arrays.retry_interval = ""
redis.pconnect.pooling_enabled = 1
redis.pconnect.connection_pooling_factor = 1.0
redis.pconnect.pool_pattern = ""
redis.backoff.algorithm = 1
redis.backoff.base = 2
redis.backoff.cap = 0.1 