/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "l5-swagger.default.api": [],
    "l5-swagger.default.docs": [],
    "l5-swagger.default.asset": [
        {
            "name": "asset",
            "required": true
        }
    ],
    "l5-swagger.default.oauth2_callback": [],
    "sanctum.csrf-cookie": [],
    "articles.store": [],
    "articles.update": [
        {
            "name": "article",
            "required": true,
            "binding": "id"
        }
    ],
    "articles.destroy": [
        {
            "name": "article",
            "required": true,
            "binding": "id"
        }
    ],
    "tags.index": [],
    "tags.store": [],
    "tags.show": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "tags.update": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "tags.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "articles.index": [],
    "articles.show": [
        {
            "name": "article",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.articles": [],
    "admin.articles.create": [],
    "admin.articles.store": [],
    "admin.articles.edit": [
        {
            "name": "article",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.articles.update": [
        {
            "name": "article",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.articles.destroy": [
        {
            "name": "article",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.statistics": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
